### ISSUE TITLE
Creating complex pattern

### ISSUE THREAD

**Issue by zangzh17** [Karel-Tavernier/gerber_writer#6]
Just found this lib is very useful in creating photomasks, but I have an issue when I tried to create some complex structure. I tried to create a ring by defining Path, but I found for some Gerber reader, the structure is not correct. Maybe it is because some points on the path are overlapped in creating a ring. Also I found if I use the arc tool to first create the left side of the ring and then the right side, the orientation setting of the ArcTo tool is not working. No longer how I choose it (+ or -), the arc is always oriented to one side. **I think to add some shape operation tools such as subtraction, merge or invert would be highly helpful.**

**Comment by Karel-Tavernier** [comment]
I am not sure I correctly understand the issue you raise.
-> Please send the offending Gerber file, which image you expect, and what exactly happens on which reader.
About the ring. I understand the following. You need to create a ring, which is a region with a hole in it. You define the outer contour as a path in one orientation, and the inner contour as a path in the other orientation, and this does not work.
-> Is this the issue with the ring? If not, please clarify, and send a sample file with expected image.
Note that this is not the way regions with holes are identified in Gerber. As mentioned in the add_region in the documentation, how contours must be constructed is explained in detail in section 4.10.3 in the Gerber Layer Format Specification, available at the www.ucamco.com website.

**Comment by Karel-Tavernier** [comment]
Hello,

I posted a reaction on github.

With kind regards,

Karel

From: zangzh17 ***@***.***>
Sent: Wednesday, 17 April 2024 23:59
To: Karel-Tavernier/gerber_writer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Karel-Tavernier/gerber_writer] Creating complex pattern (Issue #6)


Just found this lib is very useful in creating photomasks, but I have an issue when I tried to create some complex structure. I tried to create a ring by defining Path, but I found for some Gerber reader, the structure is not correct. Maybe it is because some points on the path are overlapped in creating a ring. Also I found if I use the arc tool to first create the left side of the ring and then the right side, the orientation setting of the ArcTo tool is not working. No longer how I choose it (+ or -), the arc is always oriented to one side. I think to add some shape operation tools such as subtraction, merge or invert would be highly helpful.

-

**Comment by zangzh17** [comment]
I have found that the problems seems due to the gerber renderer I used, which is pygerber. When I try to create for example a half ring, changing the orientation of the Arcs to '+' or '-' makes no difference for the rendered picture. But I found [https://gerber.ucamco.com/](url) gives me expected results. The code has been attatched for your reference. Thank you again for your great work in this project. It helps a lot.

```
from gerber_writer import DataLayer, Path, Circle
from pygerber.gerberx3.api.v2 import ColorScheme, GerberFile, PixelFormatEnum


top = DataLayer('Copper,L1,Top,Signal')

outer_diameter = 1
inner_diameter = 0.8

# define a left half ring by Path
# centered at (0,0)
top_outer_center = (0,outer_diameter)
top_inner_center = (0,inner_diameter)
bottom_outer_center = (0,-outer_diameter)
bottom_inner_center = (0,-inner_diameter)
ring = Path()
ring.moveto(top_outer_center)
ring.arcto(bottom_outer_center,(0,0), '-')
ring.lineto(bottom_inner_center)
ring.arcto(top_inner_center,(0,0), '+')
ring.lineto(top_outer_center)
top.add_region(ring,'Conductor',negative=False)

# define a right half ring by Path
# centered at (2,0)
top_outer_center = (2,outer_diameter)
top_inner_center = (2,inner_diameter)
bottom_outer_center = (2,-outer_diameter)
bottom_inner_center = (2,-inner_diameter)
ring = Path()
ring.moveto(top_outer_center)
ring.arcto(bottom_outer_center,(2,0), '+')
ring.lineto(bottom_inner_center)
ring.arcto(top_inner_center,(2,0), '-')
ring.lineto(top_outer_center)
top.add_region(ring,'Conductor',negative=False)

# save gerber
filename = '.\\gerbers\\test.gbr'
with open(filename, 'w') as outfile:
    top.dump_gerber(outfile)

# Render gerber to png picture
GerberFile.from_file(
    filename
).parse().render_raster(
    "output.png",
    dpmm=500,
    color_scheme=ColorScheme.COPPER_ALPHA,
    pixel_format=PixelFormatEnum.RGBA,
)
```

**Comment by Karel-Tavernier** [comment]
Thanks for the explanation and code.  If I understand this right, no change in the writer is needed, and I can close the issue.
Correct?
Thanks for your kind words about the project.  If you like the library, a star would be much appreciated, and be a signal to other potential users.
